name: "Feature Request"
description: Suggest a new idea or enhancement for this project
body:
  - type: markdown
    attributes:
      value: Please provide a clear and concise title for your feature request
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you are requesting in detail. Explain what problem it solves or what value it adds to the project.
